---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:14
    when:
      event: push
    commands:
      - yarn --frozen-lockfile --ignore-scripts

  - name: lint
    image: node:14
    when:
      event: push
    depends_on:
      - setup
    commands:
      - cd webapp
      - yarn run eslint . && yarn run prettier -c '**/*.+(js|jsx|json|css|md)'

