---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:10
    when:
      event: push
    commands:
      - yarn --frozen-lockfile --ignore-scripts

  - name: lint
    image: node:10
    when:
      event: push
    commands:
      - yarn run eslint 'src/**/*.{js,ts,tsx}' && yarn run prettier -c '**/*.+(js|jsx|json|css|md)'

